name: TrAISS
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _py-xgboost-mutex=2.0
  - aiohttp=3.7.4.post0
  - argon2-cffi=20.1.0
  - async-timeout=3.0.1
  - async_generator=1.10
  - attrs=20.3.0
  - blas=1.0
  - bleach=3.3.0
  - blinker=1.4
  - bokeh=2.3.3
  - bottleneck=1.3.2
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2021.5.30
  - catalogue=1.0.0
  - catboost=0.26
  - certifi=2021.5.30
  - cffi=1.14.5
  - cftime=1.5.0
  - chardet=4.0.0
  - cloudpickle=1.6.0
  - confuse=1.4.0
  - cryptography=3.4.7
  - cudatoolkit=9.2
  - curl=7.71.1
  - cycler=0.10.0
  - cymem=2.0.5
  - cython-blis=0.7.4
  - cytoolz=0.9.0.1
  - dask=2021.7.2
  - dask-core=2021.7.2
  - dataclasses=0.8
  - decorator=5.0.5
  - defusedxml=0.7.1
  - dill=0.2.9
  - distributed=2021.7.2
  - entrypoints=0.3
  - freetype=2.10.4
  - fsspec=2021.7.0
  - future=0.18.2
  - hdf4=4.2.13
  - hdf5=1.10.6
  - heapdict=1.0.1
  - htmlmin=0.1.12
  - idna=2.10
  - imagehash=4.2.0
  - imbalanced-learn=0.8.0
  - importlib-metadata=3.7.3
  - importlib_metadata=3.7.3
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jinja2=2.11.3
  - jpeg=9b
  - json5=0.9.5
  - jsonschema=3.0.2
  - jupyter_client=6.1.12
  - jupyter_core=4.7.1
  - jupyterlab=2.2.6
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=1.2.0
  - kiwisolver=1.3.1
  - krb5=1.18.2
  - lcms2=2.12
  - libcurl=7.71.1
  - libffi=3.3
  - libllvm10=10.0.1
  - libnetcdf=4.6.1
  - libpng=1.6.37
  - libprotobuf=3.17.2
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libtiff=4.1.0
  - libxgboost=1.3.3
  - lightgbm=3.1.1
  - llvmlite=0.36.0
  - locket=0.2.0
  - lz4-c=1.9.3
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - missingno=0.4.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - msgpack-numpy=0.4.7.1
  - msgpack-python=1.0.2
  - multidict=5.1.0
  - nb_conda=2.2.1
  - nb_conda_kernels=2.3.1
  - nbclient=0.5.3
  - nbconvert=6.0.7
  - nbformat=5.1.3
  - nest-asyncio=1.5.1
  - netcdf4=1.5.7
  - networkx=2.5
  - ninja=1.10.2
  - notebook=6.3.0
  - numba=0.53.1
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=1.2.3
  - pandas-profiling=2.9.0
  - pandoc=2.12
  - pandocfilters=1.4.3
  - partd=1.2.0
  - pexpect=4.8.0
  - phik=0.11.2
  - pickleshare=0.7.5
  - pillow=8.2.0
  - pip=21.0.1
  - plac=1.1.0
  - preshed=3.0.2
  - proj=7.0.1
  - prometheus_client=0.10.0
  - prompt_toolkit=1.0.15
  - psutil=5.8.0
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pycparser=2.20
  - pydeprecate=0.3.1
  - pygments=2.8.1
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.7.9
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytorch=1.6.0
  - pytorch-lightning=1.4.4
  - pytz=2021.1
  - pyu2f=0.1.5
  - pywavelets=1.1.1
  - pyzmq=20.0.0
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - seaborn=0.11.1
  - send2trash=1.5.0
  - setuptools=52.0.0
  - simplegeneric=0.8.1
  - six=1.15.0
  - sortedcontainers=2.4.0
  - spacy=2.3.5
  - sqlite=3.35.4
  - srsly=1.0.5
  - tangled-up-in-unicode=0.1.0
  - tbb=2020.3
  - tblib=1.7.0
  - tensorboard-data-server=0.6.0
  - terminado=0.9.4
  - testpath=0.4.4
  - thinc=7.4.5
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - toolz=0.11.1
  - torchmetrics=0.5.0
  - torchtext=0.7.0
  - torchvision=0.7.0
  - tornado=6.1
  - traitlets=5.0.5
  - typing-extensions=3.10.0.0
  - typing_extensions=3.10.0.0
  - ujson=4.0.2
  - visions=0.5.0
  - wasabi=0.8.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.36.2
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xarray=0.19.0
  - xgboost=1.3.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zeromq=4.3.4
  - zict=2.0.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - readline==8.1
    - ncurses==6.2
    - libgomp==9.3.0
    - libstdcxx-ng==9.1.0
    - libgcc-ng==9.3.0
    - libgfortran-ng==7.3.0
    - py-xgboost==1.3.30
    - ld_impl_linux-64==2.33.1
    - murmurhash==1.0.50
    - libedit==3.1.20210216
    - _openmp_mutex==4.5
    - absl-py==0.10.0
    - addict==2.3.0
    - aiohttp-cors==0.7.0
    - aioredis==1.3.1
    - blessings==1.7
    - boltons==20.2.1
    - cachetools==4.1.1
    - click==7.1.2
    - colorama==0.4.4
    - colorful==0.5.4
    - de-core-news-sm==2.0.0
    - dm-tree==0.1.5
    - einops==0.3.0
    - en-core-web-sm==2.0.0
    - filelock==3.0.12
    - fire==0.4.0
    - google-api-core==1.26.3
    - google-auth==1.22.1
    - google-auth-oauthlib==0.4.1
    - googleapis-common-protos==1.53.0
    - gpustat==0.6.0
    - grpcio==1.32.0
    - hiredis==2.0.0
    - joblib==0.17.0
    - lambda-networks==0.4.0
    - markdown==3.3
    - nltk==3.5
    - nvidia-ml-py3==7.352.0
    - oauthlib==3.1.0
    - opencensus==0.7.12
    - opencensus-context==0.1.2
    - opencv-python==4.4.0.44
    - pathspec==0.8.0
    - protobuf==3.13.0
    - py-spy==0.3.5
    - pyasn1-modules==0.2.8
    - pyyaml==5.4.1
    - ray==1.2.0
    - redis==3.5.3
    - regex==2020.11.13
    - rsa==4.6
    - scikit-learn==0.23.2
    - scipy==1.5.2
    - sdeint==0.2.1
    - sklearn==0.0
    - tabulate==0.8.9
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - termcolor==1.1.0
    - torchsde==0.2.1
    - tqdm==4.50.2
    - trampoline==0.1.2
    - urllib3==1.25.10
    - werkzeug==1.0.1
    - zipp==3.3.0

